spring:
  profiles: local
  data.mongodb:
    host: 10.136.153.243
    port: 18210
    database: test
    datasource:
      max-active: 3000
      max-wait: 3000        
  servlet:
    multipart:
    max-file-size: 2048MB
    max-request-size: 2048MB    


server:
  port: 9999
  servlet:
    session:
      timeout: 10m  
      connection-timeout: 10m
  tomcat:
    max-connections: 3000
  compression:
    enabled: true
    types: text/html,text/css,application/json
    min-response-size: 2048
